# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from virtual/CaliInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CaliInfo(genpy.Message):
  _md5sum = "aa331633c72b6e8b9017db2e4147569d"
  _type = "virtual/CaliInfo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int64 marker
float64[] markerincamera_measure
float64[] markerincamera_truth
float64[] eeinbase
float64[] baseincamera
float64[] markerinee
"""
  __slots__ = ['marker','markerincamera_measure','markerincamera_truth','eeinbase','baseincamera','markerinee']
  _slot_types = ['int64','float64[]','float64[]','float64[]','float64[]','float64[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       marker,markerincamera_measure,markerincamera_truth,eeinbase,baseincamera,markerinee

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CaliInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.marker is None:
        self.marker = 0
      if self.markerincamera_measure is None:
        self.markerincamera_measure = []
      if self.markerincamera_truth is None:
        self.markerincamera_truth = []
      if self.eeinbase is None:
        self.eeinbase = []
      if self.baseincamera is None:
        self.baseincamera = []
      if self.markerinee is None:
        self.markerinee = []
    else:
      self.marker = 0
      self.markerincamera_measure = []
      self.markerincamera_truth = []
      self.eeinbase = []
      self.baseincamera = []
      self.markerinee = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.marker
      buff.write(_get_struct_q().pack(_x))
      length = len(self.markerincamera_measure)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.markerincamera_measure))
      length = len(self.markerincamera_truth)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.markerincamera_truth))
      length = len(self.eeinbase)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.eeinbase))
      length = len(self.baseincamera)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.baseincamera))
      length = len(self.markerinee)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.markerinee))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 8
      (self.marker,) = _get_struct_q().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.markerincamera_measure = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.markerincamera_truth = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.eeinbase = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.baseincamera = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.markerinee = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.marker
      buff.write(_get_struct_q().pack(_x))
      length = len(self.markerincamera_measure)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.markerincamera_measure.tostring())
      length = len(self.markerincamera_truth)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.markerincamera_truth.tostring())
      length = len(self.eeinbase)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.eeinbase.tostring())
      length = len(self.baseincamera)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.baseincamera.tostring())
      length = len(self.markerinee)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.markerinee.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 8
      (self.marker,) = _get_struct_q().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.markerincamera_measure = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.markerincamera_truth = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.eeinbase = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.baseincamera = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.markerinee = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_q = None
def _get_struct_q():
    global _struct_q
    if _struct_q is None:
        _struct_q = struct.Struct("<q")
    return _struct_q
